package fvs.taxe;

public enum Button {
    TRAIN_DROP,
    TRAIN_PLACE,
    TRAIN_ROUTE,
    VIEW_ROUTE,
    GOAL_DROP,
    GOAL_VIEW,
    OBSTACLE_DROP,
    OBSTACLE_USE,
    TRAIN_CHANGE_ROUTE,
    SKIP_RESOURCE,
    SKIP_DROP,
    ENGINEER_DROP,
    ENGINEER_USE
}
